title: MMS
description: Multimedia Systems Lecutres 
theme: just-the-docs

url: https://just-the-docs.github.io

# customize 
color_scheme: dark

footer_content: "_includes/footer_custom.html"

math: katex

# Enable table of contents
toc:
  enabled: true
  h_min: 1
  h_max: 3

# Collections for better organization
collections:
  docs:
    permalink: "/:collection/:path/"
    output: true

# Just the Docs specific settings
just_the_docs:
  # Enable support for Arabic/Persian characters in anchors
  heading_anchors: true
  heading_anchor_render: true
  # Sanitization settings to preserve RTL characters
  html_to_anchor: true
  sanitize_html_attributes: false

# Enable search with RTL support
search:
  enabled: true
  heading_level: 3
  rel_url: false
  button: true
  tokenizer_separator: /[\s/]+/
  heading_anchors: true

# Aux links for the upper right navigation
aux_links:
  "mosioc":
    - "https://github.com/mosioc"


